### ISSUE TITLE
AWS EKS - Jenkins & slave - Docker in docker

### ISSUE THREAD

**Issue by micemuni** [docker/docker-install#278] opened 2022-03-23 05:19 UTC
Hi Team,
I have deployed AWS EKS cluster, deployed Jenkins as Master POD, By using configuration as plugin i have create yaml file and there i mentioned worker-docker label. 
When ever jenkins job running then new additional worker POD will create and destroy after job completed. 

As per requirement, Inside worker i need to run  cmd -  ` docker run -v $(pwd)/reports:/usr/src/app/reports  docker-images  `  --> this docker run will generate some files and located in /usr/src/app/reports
I can see those files are present in /usr/src/app/reports but I don't see the files on source path of worker POD $(pwd)/reports. 

--- Findings: 
In worker POD - I don't see the /var/lib/docker files when i tried with volume mound 
Here is worker-docker POD Dockerfile :
```
FROM openjdk:8-jdk

RUN apt-get update -y && apt-get install -y curl sudo

#Install docker
RUN curl -sSL https://get.docker.com/ | sh

RUN curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose \
    && chmod +x /usr/local/bin/docker-compose

# Download the Jenkins Slave JAR
RUN curl --create-dirs -sSLo /usr/share/jenkins/slave.jar https://repo.jenkins-ci.org/public/org/jenkins-ci/main/remoting/3.9/remoting-3.9.jar \
	&& chmod 755 /usr/share/jenkins \
	&& chmod 644 /usr/share/jenkins/slave.jar

# Download the Jenkins Slave StartUp Script
RUN curl --create-dirs -sSLo /usr/local/bin/jenkins-slave https://raw.githubusercontent.com/jenkinsci/docker-jnlp-slave/3.27-1/jenkins-slave \
	&& chmod a+x /usr/local/bin/jenkins-slave

ENTRYPOINT ["jenkins-slave"]
```

Please help me to fix --> why /var/lib/docker folder not created ..??? 
How can i get those files to worker POD path..???

**Comment by thaJeztah** [comment] 2024-10-14 08:40
This issue tracker is meant for reporting issues with the "install" script at download.docker.com.

This ticket looks unrelated to that, and more a general support question.  For such questions, consider using one of;

- the [Discussione](https://github.com/moby/moby/discussions) on the Moby repository
- the [Docker community Slack channel](https://dockr.ly/comm-slack)
- the `docker` tags on [StackOverflow](https://stackoverflow.com/questions/tagged/docker*)
- the Docker Support Forums - https://forums.docker.com

I'm closing this ticket because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2024-10-14 08:40 UTC
Labels: invalid, question
