### ISSUE TITLE
Debian 10 Buster missing from install.sh

### ISSUE THREAD

**Issue by JanneSiren** [docker/docker-install#125] opened 2019-06-13 10:48 UTC
There are less than 4 weeks to Debian 10 Buster release. Yes, the date has already been set.
Please update the convenience script to ease the final testing of Debian 10 Buster release.

[install-sh.txt](https://github.com/docker/docker-install/files/3285570/install-sh.txt)

**Comment by misanthrophy** [comment] 2019-06-28 12:34
With the launch of the Raspberry Pi 4 and therefore Buster already available for download/install, I am also not able to install Docker properly on my Pi.

**Comment by teadur** [comment] 2019-07-01 03:39
#126 fixes it, please merge

**Comment by MichaIng** [comment] 2019-07-01 15:01
Btw until the fix is merged, one can simply manually install Docker after the installer broke:
```
sed -i 's/10/buster/' /etc/apt/sources.list.d/docker.list
apt update
apt install docker-ce docker-ce-cli
```

**Comment by teadur** [comment] 2019-07-01 20:49
Thank you for your quick action i can go back and play with my buster host deployments :)

**Comment by j616** [comment] 2019-07-03 15:25
I had to use
```
sed -i 's/10/stretch/' /etc/apt/sources.list.d/docker.list
apt update
apt install docker-ce docker-ce-cli
```
instead of what was in @MichaIng's comment for raspbian

**Comment by MichaIng** [comment] 2019-07-03 18:05
@j616 
Jep, I didn't think about that even that it got merged, the change has not yet been uploaded to: https://get.docker.com/

**Comment by ysicing** [comment] 2019-07-06 15:29
Debian Buster has been released on 2019-07-06, the change has not yet been uploaded to https://get.docker.com/  😊

**Comment by Sirtea** [comment] 2019-07-08 12:00
Not sure if still relevant, but the script (as of today), generates the apt sources line with "10" instead of "buster". This causes failure to install, and I had to change it manually, repeat the "apt update" and the "apt install docker-ce".

Should be interesting to put a link "10 -> buster" in the apt server https://download.docker.com/linux/debian/dists/ or fix the script.

Thanks

**Comment by MichaIng** [comment] 2019-07-08 12:12
@Sirtea 
> Not sure if still relevant

This is what the whole topic + solution is about 😄. The master branch already contains the fix: https://github.com/docker/docker-install/blob/master/install.sh#L297-L299
But https://get.docker.com/ still ships the old version...

Not sure if there were other relevant changes that need to be tested first but IMO things should be tested BEFORE merging into the main branch (master), so they can be uploaded immediately. But that's a question of individual schedules.

**Comment by Sirtea** [comment] 2019-07-09 08:16
Great!

Master branch release worked for me; this should count as another test on debian 10, amd64. I did:

```bash
wget -qO- https://raw.githubusercontent.com/docker/docker-install/master/install.sh | bash
```

Regards

**Comment by JesperG** [comment] 2019-07-12 22:42
I tried on a fresh Raspbian on Raspberry Pi 3B.

pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.19.57-v7+ #1244 SMP Thu Jul 4 18:45:25 BST 2019 armv7l GNU/Linux

It failed for my setup with the following command and output:

pi@raspberrypi:~ $ wget -qO- https://raw.githubusercontent.com/docker/docker-install/master/install.sh | bash
# Executing docker install script, commit: UNKNOWN
+ sudo -E sh -c 'apt-get update -qq >/dev/null'
+ sudo -E sh -c 'apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null'
+ sudo -E sh -c 'curl -fsSL "https://download.docker.com/linux/raspbian/gpg" | apt-key add -qq - >/dev/null'
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sudo -E sh -c 'echo "deb [arch=armhf] https://download.docker.com/linux/raspbian buster stable" > /etc/apt/sources.list.d/docker.list'
+ sudo -E sh -c 'apt-get update -qq >/dev/null'
+ '[' -n '' ']'
+ sudo -E sh -c 'apt-get install -y -qq --no-install-recommends docker-ce >/dev/null'
E: Package 'docker-ce' has no installation candidate

**Comment by MichaIng** [comment] 2019-07-13 13:35
@JesperG 
The Raspbian Buster branch is now available, but does not yet contain a stable component: https://download.docker.com/linux/raspbian/dists/buster/

So for now you need to go with "nightly":
```
sed -i 's/stable/nightly/' /etc/apt/sources.list.d/docker.list
apt update
apt install docker-ce
```

Or you go with stable Stretch (which at least works on Buster according to my tests): https://github.com/docker/docker-install/issues/125#issuecomment-507301690

**Comment by rradar** [comment] 2019-07-13 19:02
@MichaIng 

getting the following error when I try to install "nightly" for raspbian buster:


`sudo apt install docker-ce docker-ce-cli
````
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 docker-ce : Depends: containerd.io (>= 1.2.2-3) but it is not installable
             Recommends: aufs-tools but it is not going to be installed
             Recommends: cgroupfs-mount but it is not going to be installed or
                         cgroup-lite but it is not installable
             Recommends: git but it is not going to be installed
             Recommends: pigz but it is not going to be installed
             Recommends: libltdl7 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by MichaIng** [comment] 2019-07-13 19:46
@JanneSiren 
Fist of all I forgot to add `--no-install-recommends` to avoid installing recommendations. It's default on my systems, on yours obviously not, so better: `apt install --no-install-recommends docker-ce docker-ce-cli`

But `containerd.io` is a dependency, so the above does not solve the error.

Indeed the nightly branch does not have this package, seems to be not yet ready for use.
See Buster nightly: https://download.docker.com/linux/raspbian/dists/buster/pool/nightly/armhf/
Compare Stretch stable: https://download.docker.com/linux/raspbian/dists/stretch/pool/stable/armhf/

> containerd.io (>= 1.2.2-3)

So it would actually work with the containered.io package from Stretch stable, so:
```
cat << _EOF_ > /etc/apt/sources.list.d/docker.list
deb [arch=armhf] https://download.docker.com/linux/raspbian buster nightly
deb [arch=armhf] https://download.docker.com/linux/raspbian stretch stable
_EOF_
apt update
apt install --no-install-recommends docker-ce docker-ce-cli
```

> Setting up aufs-dkms (4.19+20190211-1) ...
> Loading new aufs-4.19+20190211 DKMS files...
> It is likely that 4.19.57-v7+ belongs to a chroot's host
> Building for 4.19.57+, 4.19.57-v7+ and 4.19.57-v7l+
> Building initial module for 4.19.57+
> Error! Bad return status for module build on kernel: 4.19.57+ (armv7l)
> Consult /var/lib/dkms/aufs/4.19+20190211/build/make.log for more information.
> dpkg: error processing package aufs-dkms (--configure):

Puhh not sure if this is related to Stretch Docker vs Buster RPi firmware repo. But actually AFAIK the firmware/kernel packages are identical it it should not matter from which distro branch they are... And it worked for me some weeks ago, but this was before RPi4 compatible Raspbian Buster (+related firmware updates) were released.

Which RPi do you use? You could try to remove non-matching kernel from `/boot` and `/lib/modules`. `4.19.57+` is RPi1+Zero, `4.19.57-v7+` is RPi2+3 and `4.19.57-v7l+` is RPi4. `uname -a` to be 100% sure which kernel is in use. However I would go with the above solution first, to grab `containerd.io` from Stretch + Docker from Buster nightly.

**Comment by rradar** [comment] 2019-07-14 13:38
> ```
> cat << _EOF_ > /etc/apt/sources.list.d/docker.list
> deb [arch=armhf] https://download.docker.com/linux/raspbian buster nightly
> deb [arch=armhf] https://download.docker.com/linux/raspbian stretch stable
> _EOF_
> apt update
> apt install --no-install-recommends docker-ce docker-ce-cli
> ```
@MichaIng I did this now, purged my installed docker-ce and docker-ce-cli and tried again with
`apt install --no-install-recommends docker-ce docker-ce-cli`

Now I get this error here:

> It is likely that 4.19.57-v7+ belongs to a chroot's host
> Building for 4.19.57+, 4.19.57-v7+ and 4.19.57-v7l+
> Building initial module for 4.19.57+
> Error! Bad return status for module build on kernel: 4.19.57+ (armv7l)
> Consult /var/lib/dkms/aufs/4.19+20190211/build/make.log for more information.
> dpkg: error processing package aufs-dkms (--configure):
>  installed aufs-dkms package post-installation script subprocess returned error exit status 10
> Setting up docker-ce (5:18.09.0~3-0~raspbian-stretch) ...
> update-alternatives: using /usr/bin/dockerd-ce to provide /usr/bin/dockerd (dockerd) in auto mode
> Processing triggers for man-db (2.8.5-2) ...
> Errors were encountered while processing:
>  aufs-dkms
> E: Sub-process /usr/bin/dpkg returned an error code (1)

I use a raspberry 3 (4.19.57-v7+)

**Comment by rradar** [comment] 2019-07-14 13:39
`cat /var/lib/dkms/aufs/4.19+20190211/build/make.log
`

```
DKMS make.log for aufs-4.19+20190211 for kernel 4.19.57+ (armv7l)
Sun Jul 14 15:35:54 CEST 2019
make: Entering directory '/var/lib/dkms/aufs/4.19+20190211/build'
-I/var/lib/dkms/aufs/4.19+20190211/build/include -DCONFIG_AUFS_FS_MODULE -UCONFIG_AUFS -DCONFIG_AUFS_BRANCH_MAX_127 -DCONFIG_AUFS_SBILIST
make -C /lib/modules/4.19.57+/build M=/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs EXTRA_CFLAGS="-I/var/lib/dkms/aufs/4.19+20190211/build/include -DCONFIG_AUFS_FS_MODULE -UCONFIG_AUFS -DCONFIG_AUFS_BRANCH_MAX_127 -DCONFIG_AUFS_SBILIST" modules
make[1]: Entering directory '/usr/src/linux-headers-4.19.57+'
  CC [M]  /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/module.o
  CC [M]  /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/sbinfo.o
  CC [M]  /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.o
  CC [M]  /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.o
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.h:33,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:38,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/sbinfo.c:23:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.h:134:2: error: unknown type name ‘vfs_readf_t’
  vfs_readf_t  si_xread;
  ^~~~~~~~~~~
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.h:33,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:38,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/module.c:25:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.h:134:2: error: unknown type name ‘vfs_readf_t’
  vfs_readf_t  si_xread;
  ^~~~~~~~~~~
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.h:135:2: error: unknown type name ‘vfs_writef_t’
  vfs_writef_t  si_xwrite;
  ^~~~~~~~~~~~
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.h:135:2: error: unknown type name ‘vfs_writef_t’
  vfs_writef_t  si_xwrite;
  ^~~~~~~~~~~~
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.h:33,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:38,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.c:25:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.h:134:2: error: unknown type name ‘vfs_readf_t’
  vfs_readf_t  si_xread;
  ^~~~~~~~~~~
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.h:135:2: error: unknown type name ‘vfs_writef_t’
  vfs_writef_t  si_xwrite;
  ^~~~~~~~~~~~
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:38,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/module.c:25:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.h:243:20: error: unknown type name ‘vfs_readf_t’; did you mean ‘key_ref_t’?
 ssize_t xino_fread(vfs_readf_t func, struct file *file, void *buf, size_t size,
                    ^~~~~~~~~~~
                    key_ref_t
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:38,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/sbinfo.c:23:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.h:243:20: error: unknown type name ‘vfs_readf_t’
 ssize_t xino_fread(vfs_readf_t func, struct file *file, void *buf, size_t size,
                    ^~~~~~~~~~~
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.h:33,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:38,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.c:27:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.h:134:2: error: unknown type name ‘vfs_readf_t’
  vfs_readf_t  si_xread;
  ^~~~~~~~~~~
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.h:135:2: error: unknown type name ‘vfs_writef_t’
  vfs_writef_t  si_xwrite;
  ^~~~~~~~~~~~
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.h:245:21: error: unknown type name ‘vfs_writef_t’; did you mean ‘key_ref_t’?
 ssize_t xino_fwrite(vfs_writef_t func, struct file *file, void *buf,
                     ^~~~~~~~~~~~
                     key_ref_t
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.h:245:21: error: unknown type name ‘vfs_writef_t’; did you mean ‘pte_write’?
 ssize_t xino_fwrite(vfs_writef_t func, struct file *file, void *buf,
                     ^~~~~~~~~~~~
                     pte_write
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:38,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.c:25:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.h:243:20: error: unknown type name ‘vfs_readf_t’
 ssize_t xino_fread(vfs_readf_t func, struct file *file, void *buf, size_t size,
                    ^~~~~~~~~~~
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:38,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.c:27:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.h:243:20: error: unknown type name ‘vfs_readf_t’; did you mean ‘key_ref_t’?
 ssize_t xino_fread(vfs_readf_t func, struct file *file, void *buf, size_t size,
                    ^~~~~~~~~~~
                    key_ref_t
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.h:245:21: error: unknown type name ‘vfs_writef_t’; did you mean ‘pte_write’?
 ssize_t xino_fwrite(vfs_writef_t func, struct file *file, void *buf,
                     ^~~~~~~~~~~~
                     pte_write
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.h:245:21: error: unknown type name ‘vfs_writef_t’; did you mean ‘key_ref_t’?
 ssize_t xino_fwrite(vfs_writef_t func, struct file *file, void *buf,
                     ^~~~~~~~~~~~
                     key_ref_t
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:46,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/module.c:25:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/file.h: In function ‘au_vm_prfile_set’:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/file.h:334:7: error: ‘struct vm_area_struct’ has no member named ‘vm_prfile’; did you mean ‘vm_file’?
  vma->vm_prfile = file;
       ^~~~~~~~~
       vm_file
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:46,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/sbinfo.c:23:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/file.h: In function ‘au_vm_prfile_set’:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/file.h:334:7: error: ‘struct vm_area_struct’ has no member named ‘vm_prfile’; did you mean ‘vm_file’?
  vma->vm_prfile = file;
       ^~~~~~~~~
       vm_file
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:46,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.c:25:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/file.h: In function ‘au_vm_prfile_set’:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/file.h:334:7: error: ‘struct vm_area_struct’ has no member named ‘vm_prfile’; did you mean ‘vm_file’?
  vma->vm_prfile = file;
       ^~~~~~~~~
       vm_file
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:46,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.c:27:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/file.h: In function ‘au_vm_prfile_set’:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/file.h:334:7: error: ‘struct vm_area_struct’ has no member named ‘vm_prfile’; did you mean ‘vm_file’?
  vma->vm_prfile = file;
       ^~~~~~~~~
       vm_file
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:57,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/sbinfo.c:23:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/vfsub.h: In function ‘vfsub_update_time’:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/vfsub.h:233:9: error: implicit declaration of function ‘update_time’; did you mean ‘file_update_time’? [-Werror=implicit-function-declaration]
  return update_time(h_inode, ts, flags);
         ^~~~~~~~~~~
         file_update_time
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:57,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/module.c:25:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/vfsub.h: In function ‘vfsub_update_time’:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/vfsub.h:233:9: error: implicit declaration of function ‘update_time’; did you mean ‘pte_same’? [-Werror=implicit-function-declaration]
  return update_time(h_inode, ts, flags);
         ^~~~~~~~~~~
         pte_same
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:57,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.c:25:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/vfsub.h: In function ‘vfsub_update_time’:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/vfsub.h:233:9: error: implicit declaration of function ‘update_time’; did you mean ‘pte_same’? [-Werror=implicit-function-declaration]
  return update_time(h_inode, ts, flags);
         ^~~~~~~~~~~
         pte_same
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:303: /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/sbinfo.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:303: /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/module.o] Error 1
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:57,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.c:27:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/vfsub.h: In function ‘vfsub_update_time’:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/vfsub.h:233:9: error: implicit declaration of function ‘update_time’; did you mean ‘file_update_time’? [-Werror=implicit-function-declaration]
  return update_time(h_inode, ts, flags);
         ^~~~~~~~~~~
         file_update_time
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:303: /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.o] Error 1
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:303: /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.o] Error 1
make[1]: *** [Makefile:1517: _module_/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.19.57+'
make: *** [Makefile:47: fs/aufs/aufs.ko] Error 2
make: Leaving directory '/var/lib/dkms/aufs/4.19+20190211/build'

```

**Comment by MichaIng** [comment] 2019-07-14 14:22
@rradar 
Great, I just wanted to say that from the output still the Stretch package was about to be handled:
> Setting up docker-ce (5:18.09.03-0raspbian-stretch) ...

So purging + autoremoving + installing finally pulls the correct packages from Buster. If you find any issue with the setup you might want to report to the actual Docker Linux repo. E.g. I found an ongoing issue about Docker on Raspbian Buster where you could contribute in case: https://github.com/docker/for-linux/issues/709

**Comment by rradar** [comment] 2019-07-15 06:00
I don't know why but now my **docker setup** (hassio) **install fails** with:

```
[Info] Install supervisor Docker container
could not get decompression stream: fork/exec /usr/bin/unpigz: no such file or directory
```

with raspbian stretch this (`curl -sL "https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh" | bash -s -- -m raspberrypi3`) works without errors.

**Comment by MichaIng** [comment] 2019-07-15 12:15
@rradar 
> /usr/bin/unpigz: no such file or directory

https://packages.debian.org/buster/pigz: `apt install pigz`?
I would have expected Docker resolving such dependencies on it's own, however at least worth to give it a try.

**Comment by rradar** [comment] 2019-07-15 12:56
@MichaIng 

> `apt install pigz`?
> I would have expected Docker resolving such dependencies internally, however at least worth to give it a try.

This did actually help... Running the install script again and this time it succeeded!

Thank's!

**Comment by MichaIng** [comment] 2019-07-15 13:20
@rradar 
Great. Looks like docker itself uses `unpigz` when pulling containers: https://github.com/home-assistant/hassio-installer/blob/master/hassio_install.sh#L140-L143
AFAIK this is only another gzip implementation, so strange it does not use gzip..
pigz allows to use multiple cores/threads, but it should be only used, when available, else revert to use gzip. Will check bug reports...

But gzip is available on your system, right? `dpkg -l gzip`

**Comment by o-alquimista** [comment] 2019-07-15 14:51
The script from get.docker.com fails on Debian 10 Buster:
```
$ sudo sh get-docker.sh 
[sudo] senha para <username>: 
# Executing docker install script, commit: 36b78b2

Either your platform is not easily detectable or is not supported by this
installer script.
Please visit the following URL for more detailed installation instructions:

https://docs.docker.com/engine/installation/

```

$ lsb_release -a
```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

```

**Comment by Sirtea** [comment] 2019-07-16 07:02
Today, it worked for debian buster amd64, so the issue is fixed for me without modifications nor hacks.
Thank you all

```bash
gerard@debian:~$ wget -qO- get.docker.com | bash
# Executing docker install script, commit: 6bf300318ebaab958c4adc341a8c7bb9f3a54a1a
+ sudo -E sh -c 'apt-get update -qq >/dev/null'
+ sudo -E sh -c 'apt-get install -y -qq apt-transport-https ca-certificates curl gnupg >/dev/null'
+ sudo -E sh -c 'curl -fsSL "https://download.docker.com/linux/debian/gpg" | apt-key add -qq - >/dev/null'
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sudo -E sh -c 'echo "deb [arch=amd64] https://download.docker.com/linux/debian buster stable" > /etc/apt/sources.list.d/docker.list'
+ sudo -E sh -c 'apt-get update -qq >/dev/null'
+ '[' -n '' ']'
+ sudo -E sh -c 'apt-get install -y -qq --no-install-recommends docker-ce >/dev/null'
+ sudo -E sh -c 'docker version'
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 17:56:40 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:23:02 2019
  OS/Arch:          linux/amd64
  Experimental:     false
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker gerard

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.
gerard@debian:~$ 
```

**Comment by Ciantic** [comment] 2019-07-17 14:02
It didn't work with raspberry pi 4 using "get.docker.com":

```
# Executing docker install script, commit: 6bf300318ebaab958c4adc341a8c7bb9f3a54a1a
+ sudo -E sh -c apt-get update -qq >/dev/null
+ sudo -E sh -c apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sudo -E sh -c curl -fsSL "https://download.docker.com/linux/raspbian/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sudo -E sh -c echo "deb [arch=armhf] https://download.docker.com/linux/raspbian buster stable" > /etc/apt/sources.l                                ist.d/docker.list
+ sudo -E sh -c apt-get update -qq >/dev/null
+ [ -n  ]
+ sudo -E sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
E: Package 'docker-ce' has no installation candidate
pi@raspberrypi:~ $
```

**Comment by MichaIng** [comment] 2019-07-17 14:19
@Ciantic 
Please check the posts above:
```
curl -sSL get.docker.com | CHANNEL='nightly' bash
```

**Comment by Ciantic** [comment] 2019-07-17 14:34
@MichaIng I got it working, thanks. It however gave me `aufs-dkms` problems afterwards. I then used this `sudo apt-get --purge remove aufs-dkms` and it seems to throw that either.

**Comment by MichaIng** [comment] 2019-07-17 15:07
@Ciantic 
I guess aufs-dkms came from an earlier attempt to install Docker without `--no-install-recommends`.
- [aufs-tools](https://packages.debian.org/buster/aufs-tools) are a recommendation for docker-ce, but no dependency: https://download.docker.com/linux/raspbian/dists/buster/nightly/binary-armhf/Packages
- [aufs-dkms](https://packages.debian.org/buster/aufs-dkms) again is a recommendation for aufs-tools, but no dependency. But DKMS in general requires the kernel headers to be available, which is not default on RPi, thus it fails to configure.

For this reason I tend to disable recommends install by default on all systems, e.g.
```
cat << _EOF_ >> /etc/apt/apt.conf.d/99norecommends
APT::Install-Recommends "false";
APT::Install-Suggests "false";
APT::AutoRemove::RecommendsImportant "false";
APT::AutoRemove::SuggestsImportant "false";
_EOF_
```
- This prevent install of recommends by default.
- And it allows to autoremove them: `apt autoremove --purge`
  - Of course be careful with this, check if there is anything contained that you actually want. But in this case it should be marked as manual installed: `apt-mark manual package_i_need`

**Comment by redeagle84** [comment] 2020-03-23 15:24
Is this issue related with: ["Debian bionic Release' does not have a Release file" when using Docker script to install on Ubuntu18](https://github.com/docker/for-linux/issues/956) ?

**Comment by thaJeztah** [comment] 2024-07-20 14:18
closing, as debian 10 "buster" came and went

**Closed by thaJeztah** 2024-07-20 14:18 UTC
