### ISSUE TITLE
How to view files that are in a docker container or image

### ISSUE THREAD

**Issue by superchargez** [docker/docker-install#249] opened 2021-08-09 10:03 UTC
In windows I can see WSL folders under Linux as \\wsl.localhost\docker-desktop\ and \\wsl.localhost\docker-desktop-data. I installed a few apps that run fine in docker but I want to view the files that run in background, for example "hello-world". How can I view the file that runs this. I want to see/inspect the code. And would it be possible to modify it?

**Comment by thaJeztah** [comment] 2024-07-20 15:06
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- the [Discussione](https://github.com/moby/moby/discussions) on the Moby repository
- the [Docker community Slack channel](https://dockr.ly/comm-slack)
- the `docker` tags on [StackOverflow](https://stackoverflow.com/questions/tagged/docker*)
- the Docker Support Forums - https://forums.docker.com

I'm closing this ticket because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2024-07-20 15:06 UTC
