### ISSUE TITLE
running Rootless behind porxy

### ISSUE THREAD

**Issue by ktdharan** [docker/docker-install#293] opened 2022-05-23 06:04 UTC
The work-around mentioned in https://github.com/docker/docker-install/issues/150 doesn't seem to work 

" **But you need to remove --disable-host-loopback flag for rootlesskit in ~/bin/dockerd-rootless.sh: https://github.com/moby/moby/blob/1347481b9eb53c30f820df42a146aab8d06a7340/contrib/dockerd-rootless.sh#L85** " 

if the --disable-host-loopback  is removed rootless docker doesn't start at all . 

**Docker Info** : 
Server Version: 20.10.15 

We are also using cntlm proxy

**Comment by AkihiroSuda** [comment] 2022-05-23 09:43
Duplicate of https://github.com/moby/moby/issues/43630

**Comment by thaJeztah** [comment] 2024-07-20 14:50
closing as duplicate of https://github.com/moby/moby/issues/43630

**Closed by thaJeztah** 2024-07-20 14:50 UTC
