### ISSUE TITLE
Docker installation failing

### ISSUE THREAD

**Issue by CDEXX** [docker/docker-install#244] opened 2021-08-01 20:50 UTC
![image](https://user-images.githubusercontent.com/85038074/127784945-7d5c0b6b-5722-4343-8c3b-74d6ff81f680.png)

can someone help me i am new at coding and i got this error help me to solve

**Comment by DaspawnW** [comment] 2021-08-02 08:27
We have the same issue, this also reflects in docker-machine is not possible to provision new instances:

```
Aug 02 07:42:02 ip-10-227-162-213 gitlab-runner[916]: ERROR: Reading package lists...                     name=runner-wse7k3l-runner-1627890080-a9629596 operation=provision
Aug 02 07:42:02 ip-10-227-162-213 gitlab-runner[916]: ERROR: W: GPG error: https://download.docker.com/linux/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8  name=runner-wse7k3l-runner-1627890080-a9629596 operation=provision
Aug 02 07:42:02 ip-10-227-162-213 gitlab-runner[916]: ERROR: E: The repository 'https://download.docker.com/linux/ubuntu focal InRelease' is not signed.  name=runner-wse7k3l-runner-1627890080-a9629596 operation=provision
Aug 02 07:42:02 ip-10-227-162-213 gitlab-runner[916]: WARNING: Machine creation failed, trying to provision  error=exit status 1 name=runner-wse7k3l-runner-1627890080-a9629596
Aug 02 07:42:02 ip-10-227-162-213 gitlab-runner[916]: ERROR: Error running "sudo apt-get update": ssh command error:  name=runner-xzfhb4ns-gitlabrunnerdis-1627890076-02b2fd57 operation=provision
Aug 02 07:42:02 ip-10-227-162-213 gitlab-runner[916]: ERROR: command : sudo apt-get update                name=runner-xzfhb4ns-gitlabrunnerdis-1627890076-02b2fd57 operation=provision
Aug 02 07:42:02 ip-10-227-162-213 gitlab-runner[916]: ERROR: err     : exit status 100                    name=runner-xzfhb4ns-gitlabrunnerdis-1627890076-02b2fd57 operation=provision
Aug 02 07:42:02 ip-10-227-162-213 gitlab-runner[916]: ERROR: output  : Hit:1 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu focal InRelease  name=runner-xzfhb4ns-gitlabrunnerdis-1627890076-02b2fd57 operation=provision
Aug 02 07:42:02 ip-10-227-162-213 gitlab-runner[916]: ERROR: Hit:2 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu focal-updates InRelease  name=runner-xzfhb4ns-gitlabrunnerdis-1627890076-02b2fd57 operation=provision
Aug 02 07:42:02 ip-10-227-162-213 gitlab-runner[916]: ERROR: Hit:3 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu focal-backports InRelease  name=runner-xzfhb4ns-gitlabrunnerdis-1627890076-02b2fd57 operation=provision
Aug 02 07:42:02 ip-10-227-162-213 gitlab-runner[916]: ERROR: Get:4 https://download.docker.com/linux/ubuntu focal InRelease [52.1 kB]  name=runner-xzfhb4ns-gitlabrunnerdis-1627890076-02b2fd57 operation=provision
Aug 02 07:42:02 ip-10-227-162-213 gitlab-runner[916]: ERROR: Hit:5 https://artifacts.elastic.co/packages/7.x/apt stable InRelease  name=runner-xzfhb4ns-gitlabrunnerdis-1627890076-02b2fd57 operation=provision
Aug 02 07:42:02 ip-10-227-162-213 gitlab-runner[916]: ERROR: Hit:6 https://packages.wazuh.com/3.x/apt stable InRelease  name=runner-xzfhb4ns-gitlabrunnerdis-1627890076-02b2fd57 operation=provision
Aug 02 07:42:02 ip-10-227-162-213 gitlab-runner[916]: ERROR: Err:4 https://download.docker.com/linux/ubuntu focal InRelease  name=runner-xzfhb4ns-gitlabrunnerdis-1627890076-02b2fd57 operation=provision
Aug 02 07:42:02 ip-10-227-162-213 gitlab-runner[916]: ERROR:   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8  name=runner-xzfhb4ns-gitlabrunnerdis-1627890076-02b2fd57 operation=provision
Aug 02 07:42:02 ip-10-227-162-213 gitlab-runner[916]: ERROR: Hit:7 http://security.ubuntu.com/ubuntu focal-security InRelease  name=runner-xzfhb4ns-gitlabrunnerdis-1627890076-02b2fd57 operation=provision
Aug 02 07:42:02 ip-10-227-162-213 gitlab-runner[916]: ERROR: Reading package lists...                     name=runner-xzfhb4ns-gitlabrunnerdis-1627890076-02b2fd57 operation=provision
Aug 02 07:42:02 ip-10-227-162-213 gitlab-runner[916]: ERROR: W: GPG error: https://download.docker.com/linux/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8  name=runner-xzfhb4ns-gitlabrunnerdis-1627890076-02b2fd57 operation=provision
Aug 02 07:42:02 ip-10-227-162-213 gitlab-runner[916]: ERROR: E: The repository 'https://download.docker.com/linux/ubuntu focal InRelease' is not signed.  name=runner-xzfhb4ns-gitlabrunnerdis-1627890076-02b2fd57 operation=provision
Aug 02 07:42:02 ip-10-227-162-213 gitlab-runner[916]: WARNING: Problem while reading command output       error=read |0: file already closed
```

![install-docker](https://user-images.githubusercontent.com/2182549/127829025-a220bc70-7492-4ee6-9e4f-bbbfdf20e8ff.png)

**Comment by GlenCooper** [comment] 2021-08-04 19:16
Trying to set up docker on Ubuntu 20.04.2 LTS by following https://docs.docker.com/engine/install/debian/
This fails as well.  See [https://pastebin.com/AZ2eYY4w](https://pastebin.com/AZ2eYY4w)
I noticed the 404 error when doing a "sudo apt-get update".  I'm sure that has something to do with it...?

**Comment by bemasc** [comment] 2021-08-24 20:07
I was also able to reproduce this on a fresh Google Compute Engine Instance of Ubuntu 20.04.2.

This issue appears to be affecting a large number of Docker users.  See e.g. https://github.com/docker/for-linux/issues/905, or search Google for "7EA0A9C3F273FCD8".

**Comment by WarenGonzaga** [comment] 2021-09-01 11:53
Still not resolve this? I'm having the same issue.

**Comment by thaJeztah** [comment] 2021-09-01 12:16
@GlenCooper looks like you may have the incorrect repository configured in your apt config; I see it has the `debian` repository configured (not `ubuntu`), so it won't find packages for `focal` (as there's no Debian "focal");

```
E: The repository 'https://download.docker.com/linux/debian focal Release' does not have a Release file.
```

**Comment by thaJeztah** [comment] 2021-09-01 12:16
I'm trying to reproduce the issue, but so far haven't been able to. This is from a fresh Ubuntu 20.10 install;


```bash
curl -fsSL https://get.docker.com | sh -
# Executing docker install script, commit: 93d2499759296ac1f9c510605fef85052a2c32be
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl gnupg >/dev/null
debconf: delaying package configuration, since apt-utils is not installed
+ sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | gpg --dearmor --yes -o /usr/share/keyrings/docker-archive-keyring.gpg
+ sh -c echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends  docker-ce-cli docker-scan-plugin docker-ce >/dev/null
debconf: delaying package configuration, since apt-utils is not installed
+ version_gte 20.10
+ [ -z  ]
+ return 0
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker-ce-rootless-extras >/dev/null
debconf: delaying package configuration, since apt-utils is not installed

================================================================================

To run Docker as a non-privileged user, consider setting up the
Docker daemon in rootless mode for your user:

    dockerd-rootless-setuptool.sh install

Visit https://docs.docker.com/go/rootless/ to learn about rootless mode.


To run the Docker daemon as a fully privileged service, but granting non-root
users access, refer to https://docs.docker.com/go/daemon-access/

WARNING: Access to the remote API on a privileged Docker daemon is equivalent
         to root access on the host. Refer to the 'Docker daemon attack surface'
         documentation for details: https://docs.docker.com/go/attack-surface/

================================================================================
```

**Comment by thaJeztah** [comment] 2021-09-01 12:18
Ehm. meant Ubuntu 20.04, not 20.10

**Comment by WarenGonzaga** [comment] 2021-09-01 15:18
I solve mine when I use this ``sudo apt-get install docker.io`` everything works. I use ubuntu 20.04 on AWS lightsail.

**Comment by hmag** [comment] 2021-10-03 16:39
Hi,
I had the same issue (using Debian 11 container from LXD) and fixed it using [this answer](https://stackoverflow.com/a/68764068)
My guess is that a `chmod a+r /usr/share/keyrings/docker-archive-keyring.gpg` should be added in the script line 631.
Hervé

**Comment by fortuna** [comment] 2021-11-01 18:30
It seems like https://github.com/docker/docker-install/pull/256 may fix the issue?

Can we get that merged?

**Closed** 2022-03-21 15:09 UTC

**Comment by glaciomarine** [comment] 2023-09-12 02:12
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7EA0A9C3F273FCD8
Executing: /tmp/apt-key-gpghome.4RW19WYf92/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 7EA0A9C3F273FCD8
gpg: key 8D81803C0EBFCD88: 1 duplicate signature removed
gpg: 密钥 8D81803C0EBFCD88：“Docker Release (CE deb) <docker@docker.com>” 未改变
gpg: 处理的总数：1
gpg:              未改变：1

**Comment by GlenCooper** [comment] 2023-10-09 05:47
> @GlenCooper looks like you may have the incorrect repository configured in your apt config; I see it has the `debian` repository configured (not `ubuntu`), so it won't find packages for `focal` (as there's no Debian "focal");
> 
> ```
> E: The repository 'https://download.docker.com/linux/debian focal Release' does not have a Release file.
> ```

Thanks for spotting that.  I'm sure that had something to do with the problem I saw.  Good news is that I now have Docker installed and working great on Ubuntu 22.04.  Thanks for your help!
