### ISSUE TITLE
docker installation error

### ISSUE THREAD

**Issue by hariharan382** [docker/docker-install#315] opened 2022-10-08 06:09 UTC
HI i am trying to install Docker, but after following few preliminaries, before instalation i tried to update  but could not update , I eve purged the installation still i could not get rid of this error

drint@drint:~$ sudo apt-get update

Hit:1 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu focal InRelease
Hit:2 http://in.archive.ubuntu.com/ubuntu focal InRelease                                                               
Get:3 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]                                               
Ign:4 https://download.docker.com/linux ubuntu InRelease                                          
Hit:5 http://packages.ros.org/ros/ubuntu focal InRelease                                                                          
Hit:6 https://download.docker.com/linux/ubuntu focal InRelease                                                                    
Get:7 http://in.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]                                   
Err:8 https://download.docker.com/linux ubuntu Release                                                                 
  404  Not Found [IP: 65.8.72.116 443]
Hit:9 https://dl.google.com/linux/chrome/deb stable InRelease                                                          
Get:10 http://in.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]   
Reading package lists... Done       
E: The repository 'https://download.docker.com/linux ubuntu Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by manoj0077** [comment] 2022-10-16 22:28
It looks like https://download.docker.com/linux/ubuntu/dists/focal/stable/binary-amd64/Packages.bz2 has a wrong md5 checksum entered in release file. Can we please correct this?

**Comment by thaJeztah** [comment] 2022-10-17 00:09
@manoj0077 do you have details? how does the issue manifest itself? I tried installing on Ubuntu focal, but didn't see any failures.

**Comment by manoj0077** [comment] 2022-10-17 00:20
https://download.docker.com/linux/ubuntu/dists/focal/ --> release file has 5cd3a78c6ac14224d8cb837e4a3aee17            19260 stable/binary-amd64/Packages.bz2

But in reality https://download.docker.com/linux/ubuntu/dists/focal/stable/binary-amd64/Packages.bz2  has a different checksum. 

Hashes of expected file:\n - Filesize:18519 [weak]\n - SHA512:25ae8d060506d811c6e53f43b08e3bc9a95de020606dae54e5f8770384b50cbbde50307085d66d2020e10431025331e788ba0e4208f734fc8cfafe18b1f0bcff\n - SHA256:bff1fb7605fad668dc36da2a8ab9e8c864d48266d2859c35bd51ad38247181ff\n - SHA1:836ec0a727741aebd12b599656dc715b830a6dfe [weak]\n - MD5Sum:9d0854226ca04178e142c0bb32139451 [weak]\nRelease file created at: Wed, 05 Oct 2022 15:08:31 +0000\n, E:Some index files failed to download.

**Comment by thaJeztah** [comment] 2022-10-17 13:36
I'm not able to reproduce; checksum seems to match:

```bash
curl -fsSL https://download.docker.com/linux/ubuntu/dists/focal/stable/binary-amd64/Packages.bz2 | md5
5cd3a78c6ac14224d8cb837e4a3aee17
```

**Comment by manoj0077** [comment] 2022-10-18 01:02
yup I am not seeing this issue anymore.

**Comment by thaJeztah** [comment] 2022-10-18 12:30
Perhaps it was caching somewhere (although our CDN cache should be invalidated when we publish new packages).

Let me close this ticket for now 👍

**Closed by thaJeztah** 2022-10-18 12:30 UTC
